version: '3'
services:
  bot:
    build: .
    ports:
      - "8080:80"
    environment:
      - TELEGRAM_BOT_TOKEN=your_bot_token_here
      - ADMIN_ID=your_admin_id_here
      - BOT_USERNAME=CRYPTOCAP_ROBOT
      - CHANNEL_ID=@your_channel
    volumes:
      - .:/var/www/html