services:
  - type: web
    name: botdoc
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Укажите значение в панели Render.com
      - key: ADMIN_ID
        sync: false # Укажите значение в панели Render.com
      - key: BOT_USERNAME
        sync: false # Укажите значение в панели Render.com
    numInstances: 1
    healthCheckPath: /
    port: 80
